### PR TITLE
docs(no-multiple-actions-in-effects): satisfy other rules

### PR DESCRIPTION
**Pull request by dangrussell**
examples satisfy prefer-effect-callback-in-block-statement

Also removed "$" from constructor parameters

### CODE REVIEW

**Review by timdeschryver — COMMENTED** [review]
Hi, thanks to align the rules in this PR!
The examples in NgRx are all using `actions$`, so I would like to keep this aligned (I think it could otherwise even be a warning if you're using the rxjs eslint rules).
Do you want to update the docs so they use `actions$`?

**Comment by dangrussell** [comment]
> Do you want to update the docs so they use `actions$`?

Will do!

**Comment by timdeschryver** [comment]
@dangrussell I'm sorry to be a pain, but this would als mean that we should update the usage of `this.actions` in the examples. These should also be renamed to `this.actions$`.

**Comment by dangrussell** [comment]
> @dangrussell I'm sorry to be a pain, but this would als mean that we should update the usage of `this.actions` in the examples. These should also be renamed to `this.actions$`.

Ah, I see. I was restoring the previous names. I will make them all use the $. One more commit coming :)

**Review by timdeschryver — APPROVED** [review]

**Comment by timdeschryver** [comment]
@all-contributors please add @dangrussell  for docs

**Pull request merged**
