### PR TITLE
refactor: remove `dist` import references

### PR DESCRIPTION
**Pull request by rafaelss95**
A small change that replaces `dist` references on import statement.

### CODE REVIEW

**Comment by rafaelss95** [comment]
@timdeschryver I did a fresh install with `yarn` and after ran `git commit`, `pre-commit` script didn't run and I got two warnings:

> hint: The '.husky/pre-commit' hook was ignored because it's not set as executable.
> hint: You can disable this warning with `git config advice.ignoredHook false`.

Do you know if it's something related to my setup or...?

**Review by timdeschryver — APPROVED** [review]

**Comment by timdeschryver** [comment]
About the pre-commit... yarn should have installed the needed hooks after the installation (https://github.com/timdeschryver/eslint-plugin-ngrx/blob/main/package.json#L48). Are you using yarn 2?

**Comment by rafaelss95** [comment]
> About the pre-commit... yarn should have installed the needed hooks after the installation (https://github.com/timdeschryver/eslint-plugin-ngrx/blob/main/package.json#L48). Are you using yarn 2?

I'm running yarn 1.19.1.

**Comment by timdeschryver** [comment]
👍 I'll have a look at it later this week, thanks for letting me know!

**Comment by timdeschryver** [comment]
hmm. I'm not able to reproduce it (with npm and yarn).
Did you perhaps encounter an error after/while installing the deps? 

After the installation, you should normally see the following message.
```ts
$ husky install
$ husky - Git hooks installed
```

**Comment by rafaelss95** [comment]
Thanks for taking a look on this... I got no errors while installing. Here's the full log (I removed `node_modules` and reinstalled everything from scratch):

> % yarn
yarn install v1.19.1
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
warning jest > @jest/core > jest-haste-map > sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
warning jest > @jest/core > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning jest > @jest/core > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > tsutils-etc@1.3.4" has unmet peer dependency "tsutils@^3.0.0".
warning " > @angular/core@12.1.2" has unmet peer dependency "zone.js@~0.11.4".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.22.5", while you're on "1.19.1".
info To upgrade, run the following command:
$ brew upgrade yarn
$ husky install
husky - Git hooks installed
✨  Done in 67.96s.

**Pull request merged**
